EmployeeManagement_Demo/Controllers/AdministratorController.cs
using EmployeeManagement_Demo.Models;
using EmployeeManagement_Demo.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.Security.Claims;

namespace EmployeeManagement_Demo.Controllers
{
    [Authorize(Roles ="Admin")]
    public class AdministratorController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<ApplicationUser> userManager;

        public AdministratorController(RoleManager<IdentityRole> roleManager,
                                        UserManager<ApplicationUser> userManager)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
        }

        [HttpGet]
        [Authorize(policy: "CreateRolePolicy")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(policy: "CreateRolePolicy")]
        public async Task<IActionResult> Create(AdminViewModel model)
        {
            if(ModelState.IsValid)
            {
                IdentityRole identityRole = new IdentityRole()
                {
                    Name = model.RoleName
                };

                var result = await roleManager.CreateAsync(identityRole);
                if (result.Succeeded) 
                    return RedirectToAction("GetAllRoles");

                foreach (var error in  result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }
   
            return View(model);
        }


        [HttpPost]
        [Authorize(policy: "DeleteRolePolicy")]
        public async Task<IActionResult> DeleteUser(string id)
        {
            if (id == null)
                return BadRequest();

            ApplicationUser user = await userManager.FindByIdAsync(id);
            if (user == null)
                return NotFound();

            var reuslt = await userManager.DeleteAsync(user);
            
            if(reuslt.Succeeded)
                return RedirectToAction(nameof(UsersList));
           
            foreach (var error in reuslt.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }

            return RedirectToAction(nameof(UsersList));
        }


        [HttpPost]
        [Authorize(policy: "DeleteRolePolicy")]
        public async Task<IActionResult> DeleteRole(string id)
        {
            if (id == null)
                return BadRequest();

            var role = await roleManager.FindByIdAsync(id);

            if (role == null)
                return NotFound();

            var reuslt = await roleManager.DeleteAsync(role);

            if (reuslt.Succeeded)
                return RedirectToAction(nameof(GetAllRoles));

            foreach (var error in reuslt.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }

            return RedirectToAction(nameof(GetAllRoles));
        }


        [HttpGet]
        public async Task<IActionResult> ManageUserRole(string userId)
        {
            ViewBag.UserId = userId;    
            if (userId == null)
                return BadRequest();

            var user = await userManager.FindByIdAsync(userId);

            if (user == null)
                return NotFound();

            var model = new List<ManageUserRoleViewModel>();

            foreach(var role in roleManager.Roles.ToList())
            {
                var mangeUserRoleModel = new ManageUserRoleViewModel
                {
                    RoleId = role.Id,
                    RoleName = role.Name,
                    IsSelected = await userManager.IsInRoleAsync(user, role.Name)
                };
            
                model.Add(mangeUserRoleModel);
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> ManageUserRole(List<ManageUserRoleViewModel> model, string userId)
        {
            if (userId == null)
                return BadRequest();

            if (ModelState.IsValid)
            {
                ApplicationUser user = await userManager.FindByIdAsync(userId);
                if(user == null)
                    return NotFound();

                var roles = await userManager.GetRolesAsync(user);
                var result = await userManager.RemoveFromRolesAsync(user, roles);

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", "Cannot remove this user from the Roles");
                    return View(model);
                }

                result = await userManager.AddToRolesAsync(user, model.Where(x => x.IsSelected == true)
                    .Select(x => x.RoleName));

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", "Cannot Add Role for this User");
                    return View(model);
                }         
            }

            return RedirectToAction(nameof(EditUser), new { id = userId });
        }


        [HttpGet]
        public async Task<IActionResult> ManageUserClaim(string userId)
        {
            if (userId == null) return BadRequest();
            var user = await userManager.FindByIdAsync(userId);

            if (user == null) return NotFound();

            var existingUserClaims = await userManager.GetClaimsAsync(user);

            var model = new UserClaimsViewModel
            {
                userId = user.Id,               
            };

            foreach (var claim in ClaimStore.AllClaims)
            {
                UserClaim userClaim = new UserClaim
                {
                    ClaimType = claim.Type,
                    IsSelected = existingUserClaims.Any(c => c.Type == claim.Type)
                };

                model.Claims.Add(userClaim);
            }

            return View(model);

        }

        [HttpPost]
        public async Task<IActionResult> ManageUserClaim(UserClaimsViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await userManager.FindByIdAsync(model.userId);
                if (user == null) return NotFound();

                var claims = await userManager.GetClaimsAsync(user);
                var result = await userManager.RemoveClaimsAsync(user, claims);

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", "Cannot Remove Claims from this User");
                    return View(model);
                }

                result = await userManager.AddClaimsAsync(user, model.Claims.Where(c => c.IsSelected == true)
                                                            .Select(c => new Claim(c.ClaimType, c.ClaimType)));
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", "Cannot Remove Claims from this User");
                    return View(model);
                }

            }
            return RedirectToAction(nameof(EditUser), new { id = model.userId });
        }

        [HttpGet]
        public IActionResult UsersList()
        {
            var users = userManager.Users.ToList();
            return View(users);
        }

        [HttpGet]
        public IActionResult GetAllRoles()
        {
            var roleList = roleManager.Roles.ToList();
            return View(roleList);
        }

        [HttpGet]
        [Authorize(policy: "EditRolePolicy")]
        public async Task<IActionResult> EditRole(string id)
        {
           var role = await roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }

            var model = new EditRoleViewModel { 
                Id = role.Id,
                RoleName = role.Name
               
            };

            foreach (var user in userManager.Users.ToList())
            {
                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    model.Users.Add(user.UserName);
                }
            }


            return View(model);
        }

        [HttpPost]
        [Authorize(policy: "EditRolePolicy")]
        public async Task<IActionResult> EditRole(EditRoleViewModel model)
        {
            if(ModelState.IsValid)
            {
                var role = await roleManager.FindByIdAsync(model.Id);
                if(role == null)
                {
                    return NotFound();
                }

                role.Name = model.RoleName;
                var result = await roleManager.UpdateAsync(role);

                if (result.Succeeded)
                {
                    return RedirectToAction(nameof(GetAllRoles));
                }
                
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }

            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> EditUserInRole(string roleId)
        {
            ViewBag.roleId = roleId;

            var role = await roleManager.FindByIdAsync(roleId);
            if (role == null)
            {
                return NotFound();
            }

            var model = new List<UserRoleViewModel>();
            foreach(var user in userManager.Users.ToList())
            {
                var userRoleViewModel = new UserRoleViewModel
                {
                    UserId = user.Id,
                    UserName = user.UserName,                   
                };
                if (await userManager.IsInRoleAsync(user, role.Name))
                    userRoleViewModel.IsSelected = true;

EmployeeManagement_Demo/Controllers/EmployeeController.cs
using EmployeeManagement_Demo.Models;
using EmployeeManagement_Demo.Services;
using EmployeeManagement_Demo.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EmployeeManagement_Demo.Controllers
{
    [Authorize]
    public class EmployeeController : Controller
    {
        private readonly IEmployeeReprository employeeReprository;

        public EmployeeController(IEmployeeReprository employeeReprository)
        {
            this.employeeReprository = employeeReprository;
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            var model = employeeReprository.GetEmployees();
            return View(model);
        }

        [AllowAnonymous]
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            var model = employeeReprository.GetEmployeeByID(id);
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(EmployeeCreateViewModel emp)
        {
            if (emp == null)
            {
                return BadRequest();
            }
            if(ModelState.IsValid)
            {
                employeeReprository.AddEmployee(emp);
                return RedirectToAction(nameof(Index));
            }
            
            return View();
        }

        
        public IActionResult Delete(int? id)
        {
            if(id == null)
            {
                return BadRequest();
            }

            employeeReprository.DeleteEmployee(id);
            return RedirectToAction(nameof(Index));
        }

        
        public IActionResult Edit(int? id)
        {
            if(id == null)
            {
                return BadRequest();
            }

            var employee = employeeReprository.GetEmployeeByID(id);
            if(employee == null)
                return NotFound();
            EmployeeEditViewModel model = new EmployeeEditViewModel()
            {
                id = employee.Id,
                Name = employee.Name,
                Department = employee.Department,
                Email = employee.Email,
                existedPhoto = employee.PhotoPath
                    
            };
            return View(model);
        }

        [HttpPost]
        
        public IActionResult Edit(int? id,  EmployeeEditViewModel model)
        {
            if(id==null)
                return BadRequest();
            if(ModelState.IsValid)
            {
                employeeReprository.UpdateEmployee(id, model);
                return RedirectToAction(nameof(Details), new {id });
            }
            return View(model);
        }

    }
}

EmployeeManagement_Demo/Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> signInManager;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmployeeManagement_Demo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/twitter-bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EmployeeManagement_Demo.styles.css" asp-append-version="true" />
</head>
<body>
    <header >
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EmployeeManagement_Demo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between ">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Employee" asp-action="Index">Home</a>
                        </li> 
                        
                        @if(signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                            @* <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown"
                                href="#" role="button" aria-haspopup="true" aria-expanded="false">Manage</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-controller="Administrator" asp-action="GetAllRoles">Roles</a>
                                    <a class="dropdown-item" asp-controller="Administrator" asp-action="UsersList">Users</a>
                                    
                                </div>
                            </li> *@
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-controller="Administrator" asp-action="GetAllRoles">
                                    Manage Roles
                                    </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-controller="Administrator" asp-action="UsersList">
                                    Manage Users
                                </a>
                            </li>

                            
                        }
                    </ul>
                    <ul class="navbar-nav  ml-auto">
                        @if (signInManager.IsSignedIn(User))
                        {
                            <form method="post" asp-controller="Account" asp-action="Logout">
                                <button type="submit" class="nav-link btn btn-link py-0" style="width:auto">
                                    Logout @User.Identity.Name
                                </button>
                            </form>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                        }
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - EmployeeManagement_Demo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/twitter-bootstrap/js/bootstrap.min.js"></script>
    <script src="~/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/jquery/jquery.min.js"></script>
    <script src="~/jquery-validate/jquery.validate.min.js"></script>
    <script src="~/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>